# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movieid', models.IntegerField(db_column='movieID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('categories', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'movie',
            },
        ),
    ]
