# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fts', '0002_movies'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table='movies',
        ),
    ]
