# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fts', '0003_auto_20171025_1410'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='moviedescriptions',
            table='moviedescriptions',
        ),
    ]
