"""empty message

Revision ID: 1198679324f3
Revises: bf5248f167e1
Create Date: 2019-08-07 14:44:57.168936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1198679324f3'
down_revision = 'bf5248f167e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_column('users', 'email_confirmed_at')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email_confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    # ### end Alembic commands ###
