"""empty message

Revision ID: 120247cef0a5
Revises: ea87a6729ee7
Create Date: 2019-10-05 17:40:05.469899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120247cef0a5'
down_revision = 'ea87a6729ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solved_homeworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('homework_id', sa.Integer(), nullable=False),
    sa.Column('repo_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homeworks.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subtasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtask_number', sa.Integer(), nullable=False),
    sa.Column('subtask_text', sa.Text(), nullable=False),
    sa.Column('max_points', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solved_homeworks_solutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solved_homework_id', sa.Integer(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.ForeignKeyConstraint(['solved_homework_id'], ['solved_homeworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('students_solutions')
    op.add_column('solution_groups', sa.Column('subtask_id', sa.Integer(), nullable=False))
    op.drop_constraint('solution_groups_task_id_fkey', 'solution_groups', type_='foreignkey')
    op.create_foreign_key(None, 'solution_groups', 'subtasks', ['subtask_id'], ['id'])
    op.drop_column('solution_groups', 'task_id')
    op.add_column('tasks', sa.Column('solution_filename', sa.Text(), nullable=False))
    op.drop_column('tasks', 'max_points')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('max_points', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'solution_filename')
    op.add_column('solution_groups', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'solution_groups', type_='foreignkey')
    op.create_foreign_key('solution_groups_task_id_fkey', 'solution_groups', 'tasks', ['task_id'], ['id'])
    op.drop_column('solution_groups', 'subtask_id')
    op.create_table('students_solutions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('solution_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('homework_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homeworks.id'], name='students_solutions_homework_id_fkey'),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], name='students_solutions_solution_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='students_solutions_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='students_solutions_pkey')
    )
    op.drop_table('solved_homeworks_solutions')
    op.drop_table('subtasks')
    op.drop_table('solved_homeworks')
    # ### end Alembic commands ###
