"""empty message

Revision ID: 4337f81f7398
Revises: 523201412811
Create Date: 2019-10-09 19:49:15.378701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4337f81f7398'
down_revision = '523201412811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('solved_homeworks_homework_id_fkey', 'solved_homeworks', type_='foreignkey')
    op.drop_constraint('solved_homeworks_student_id_fkey', 'solved_homeworks', type_='foreignkey')
    op.create_foreign_key(None, 'solved_homeworks', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'solved_homeworks', 'homeworks', ['homework_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('solved_homeworks_solutions_solved_homework_id_fkey', 'solved_homeworks_solutions', type_='foreignkey')
    op.drop_constraint('solved_homeworks_solutions_solution_id_fkey', 'solved_homeworks_solutions', type_='foreignkey')
    op.create_foreign_key(None, 'solved_homeworks_solutions', 'solutions', ['solution_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'solved_homeworks_solutions', 'solved_homeworks', ['solved_homework_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solved_homeworks_solutions', type_='foreignkey')
    op.drop_constraint(None, 'solved_homeworks_solutions', type_='foreignkey')
    op.create_foreign_key('solved_homeworks_solutions_solution_id_fkey', 'solved_homeworks_solutions', 'solutions', ['solution_id'], ['id'])
    op.create_foreign_key('solved_homeworks_solutions_solved_homework_id_fkey', 'solved_homeworks_solutions', 'solved_homeworks', ['solved_homework_id'], ['id'])
    op.drop_constraint(None, 'solved_homeworks', type_='foreignkey')
    op.drop_constraint(None, 'solved_homeworks', type_='foreignkey')
    op.create_foreign_key('solved_homeworks_student_id_fkey', 'solved_homeworks', 'students', ['student_id'], ['id'])
    op.create_foreign_key('solved_homeworks_homework_id_fkey', 'solved_homeworks', 'homeworks', ['homework_id'], ['id'])
    # ### end Alembic commands ###
