"""empty message

Revision ID: 4c2ba870f417
Revises: 120247cef0a5
Create Date: 2019-10-06 08:53:44.238301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2ba870f417'
down_revision = '120247cef0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solved_homeworks', sa.Column('repo_path', sa.String(length=255), nullable=False))
    op.drop_column('solved_homeworks', 'repo_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solved_homeworks', sa.Column('repo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('solved_homeworks', 'repo_path')
    # ### end Alembic commands ###
