"""empty message

Revision ID: 4d49d2a77c15
Revises: 1198679324f3
Create Date: 2019-08-07 14:58:34.325001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d49d2a77c15'
down_revision = '1198679324f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('added_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'added_at')
    # ### end Alembic commands ###
