"""empty message

Revision ID: 8d21886aade7
Revises: 244b62dad30a
Create Date: 2019-09-26 16:19:28.915721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d21886aade7'
down_revision = '244b62dad30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'enrolled_in_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('enrolled_in_year', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
