"""empty message

Revision ID: 91a31e1ef1d6
Revises: ea7e59f16f7c
Create Date: 2019-10-09 17:09:10.582217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a31e1ef1d6'
down_revision = 'ea7e59f16f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'task_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'task_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
