"""empty message

Revision ID: a5976cc7f8d5
Revises: f75d61a78c25
Create Date: 2019-10-20 22:59:54.075613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5976cc7f8d5'
down_revision = 'f75d61a78c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('solved_homeworks_solutions_solved_homeworks_id_fkey', 'solved_homeworks_solutions', type_='foreignkey')
    op.drop_constraint('solved_homeworks_solutions_solutions_id_fkey', 'solved_homeworks_solutions', type_='foreignkey')
    op.create_foreign_key(None, 'solved_homeworks_solutions', 'solutions', ['solutions_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'solved_homeworks_solutions', 'solved_homeworks', ['solved_homeworks_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solved_homeworks_solutions', type_='foreignkey')
    op.drop_constraint(None, 'solved_homeworks_solutions', type_='foreignkey')
    op.create_foreign_key('solved_homeworks_solutions_solutions_id_fkey', 'solved_homeworks_solutions', 'solutions', ['solutions_id'], ['id'])
    op.create_foreign_key('solved_homeworks_solutions_solved_homeworks_id_fkey', 'solved_homeworks_solutions', 'solved_homeworks', ['solved_homeworks_id'], ['id'])
    # ### end Alembic commands ###
