"""empty message

Revision ID: f75d61a78c25
Revises: 0bfac18e753e
Create Date: 2019-10-20 22:46:39.658990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75d61a78c25'
down_revision = '0bfac18e753e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solved_homeworks_solutions', sa.Column('solutions_id', sa.Integer(), nullable=True))
    op.add_column('solved_homeworks_solutions', sa.Column('solved_homeworks_id', sa.Integer(), nullable=True))
    op.drop_constraint('solved_homeworks_solutions_solution_id_fkey', 'solved_homeworks_solutions', type_='foreignkey')
    op.drop_constraint('solved_homeworks_solutions_solved_homework_id_fkey', 'solved_homeworks_solutions', type_='foreignkey')
    op.create_foreign_key(None, 'solved_homeworks_solutions', 'solved_homeworks', ['solved_homeworks_id'], ['id'])
    op.create_foreign_key(None, 'solved_homeworks_solutions', 'solutions', ['solutions_id'], ['id'])
    op.drop_column('solved_homeworks_solutions', 'id')
    op.drop_column('solved_homeworks_solutions', 'solved_homework_id')
    op.drop_column('solved_homeworks_solutions', 'solution_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solved_homeworks_solutions', sa.Column('solution_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('solved_homeworks_solutions', sa.Column('solved_homework_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('solved_homeworks_solutions', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'solved_homeworks_solutions', type_='foreignkey')
    op.drop_constraint(None, 'solved_homeworks_solutions', type_='foreignkey')
    op.create_foreign_key('solved_homeworks_solutions_solved_homework_id_fkey', 'solved_homeworks_solutions', 'solved_homeworks', ['solved_homework_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('solved_homeworks_solutions_solution_id_fkey', 'solved_homeworks_solutions', 'solutions', ['solution_id'], ['id'], ondelete='CASCADE')
    op.drop_column('solved_homeworks_solutions', 'solved_homeworks_id')
    op.drop_column('solved_homeworks_solutions', 'solutions_id')
    # ### end Alembic commands ###
